### ISSUE TITLE
Add in contribute.json

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/solitude#399]
Let's add in contribute.json to some of our stack in the hope of getting some contributors.

https://github.com/mozilla/contribute.json

**Comment by andymckay-limited-access** [comment]
This should probably go into payments-service, since solitude is not accessible.

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by Lord-of-Darkness** [comment]
Mozilla team! You betray the spirit of code open and another time! Fortunately, more and more people are realizing that kind of hypocrites you are!

You are never going to be the number one in the browser market! Stop thinking you could be a leader, never exceed Chrome! So stop running behind Google and again focus on geeks and power users, bring personalization back, stop adding more "Chrome parity"! Add place better "Vivaldi parity"-not from the development team, you can learn how users should be treated! With respect and with the aim of satisfying your needs instead of fleeing as it operates and betray its user base kernel and other time and again and again...

You is the Mozilla developers have a brain at all, or are you just treacherous opportunists in Google Paylist? Australis is an imitation without value of Google user interface - you betray your Open Source origins with the addition of DRM and ads... well, another step to sell, the same as add mess owner as of Pocket!

You're traitors to all related open source! Shame on you and your developers for Mozilla "out of this world" "leaders" with less than half of a brain!

I only say vivaldi.com - palemoon.org - otter-browser.org or seamonkey-project.org
