### ISSUE TITLE
Return dependable error codes for validation errors

### ISSUE THREAD

**Issue by kumar303** [mozilla/solitude#405]
For the Mozilla Payments integration, we are currently receiving some 400 error responses such as:

````
{"errors": {"uuid": ["Buyer does not exist."]}}
````

On the client side (or in ``payments-service``) we may need to catch this error and display a localized error such as "The payment cannot be completed because the product is not configured correctly." The way we achieved this in the past is instead to return reliable error codes such as:

````
{"errors": {"uuid": ["BUYER_DOES_NOT_EXIST"]}}
````

This discourages another developer from editing the error message (for example, removing a period in the sentence) and allows the client to maintain a list of expected error codes.

**Comment by kumar303** [comment]
Update: 'buyer does not exist' is not a good example because it is not user actionable. A user actionable error could be something we receive from Braintree, like:

````
{"errors": {"cc_number": ["Credit card number is invalid"]}}
````

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by Lord-of-Darkness** [comment]
Mozilla team! You betray the spirit of code open and another time! Fortunately, more and more people are realizing that kind of hypocrites you are!

You are never going to be the number one in the browser market! Stop thinking you could be a leader, never exceed Chrome! So stop running behind Google and again focus on geeks and power users, bring personalization back, stop adding more "Chrome parity"! Add place better "Vivaldi parity"-not from the development team, you can learn how users should be treated! With respect and with the aim of satisfying your needs instead of fleeing as it operates and betray its user base kernel and other time and again and again...

You is the Mozilla developers have a brain at all, or are you just treacherous opportunists in Google Paylist? Australis is an imitation without value of Google user interface - you betray your Open Source origins with the addition of DRM and ads... well, another step to sell, the same as add mess owner as of Pocket!

You're traitors to all related open source! Shame on you and your developers for Mozilla "out of this world" "leaders" with less than half of a brain!

I only say vivaldi.com - palemoon.org - otter-browser.org or seamonkey-project.org

**Comment by andymckay-limited-access** [comment]
I think #418 covers this well.
